name: "Build"

on:
  push:
    branches: "main"
  pull_request:
    branches: "*"


concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2
        with:
          persist-credentials: false

      - name: "Install uv"
        uses: "astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b" # v8.1.0

      - name: "Install dependencies"
        run: "uv sync --group dev --group test"

      - name: "Check the server extension is installed"
        run: |
          set -eux
          uv run jupyter server extension list
          uv run jupyter server extension list 2>&1 | grep -ie "jupyter_tiler.*OK"

      - name: "Test"
        run: "uv run pytest -vv -r ap --cov"

      - name: "Package the extension"
        run: "uv build"

      - name: "Upload extension packages"
        uses: "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a" # v7.0.1
        with:
          name: "extension-artifacts"
          path: "dist/jupyter_tiler*"
          if-no-files-found: "error"

  test_isolated:
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install Python"
        uses: "actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405" # v6.2.0
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: "Install uv"
        uses: "astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b" # v8.1.0

      - uses: "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c" # v8.0.1
        with:
          name: "extension-artifacts"

      - name: "Install from wheel"
        run: |
          uv pip install --system "jupyterlab>=4.0.0,<5" jupyter_tiler*.whl

      - name: "Check the server extension is installed"
        run: |
          set -eux
          jupyter server extension list
          jupyter server extension list 2>&1 | grep -ie "jupyter_tiler.*OK"
